class Idioma:

    ATUAL = "pt"

    TEXTOS = { # portugues 
        "pt": {

            # Comuns a várias telas
            "comum.id": "ID", #classe com o seu valor 
            "comum.nome": "Nome",
            "comum.novo": "Novo",
            "comum.salvar": "Salvar",
            "comum.alterar": "Alterar",
            "comum.excluir": "Excluir",
            "comum.fechar": "Fechar",
            "comum.cancelar": "Cancelar",
            "comum.confirmacao": "Confirmação",
            "comum.erro_prefixo": "Erro: ",

            # Tela de Estados
            "estado.janela_titulo": "CRUD de Estados",
            "estado.titulo": "Cadastro de Estados",
            "estado.dados_frame": "Dados do estado",
            "estado.sigla": "Sigla",
            "estado.confirmar_exclusao": "Deseja realmente excluir este estado?",
            "estado.cadastrado_sucesso": "Estado cadastrado com sucesso!",
            "estado.atualizado_sucesso": "Estado atualizado com sucesso!",
            "estado.excluido_sucesso": "Estado excluído com sucesso!",
            "estado.nao_encontrado": "Estado não encontrado.",
            "estado.selecione_da_lista": "Selecione um estado na lista.",
            "estado.erro_ao_excluir": "Problemas ao excluir estado",
            "estado.erro_sigla_tamanho": "A sigla deve possuir exatamente 2 caracteres.",

            # Tela de Fornecedores
            "fornecedor.janela_titulo": "CRUD de Fornecedores",
            "fornecedor.titulo": "Cadastro de Fornecedores",
            "fornecedor.dados_frame": "Dados do fornecedor",
            "fornecedor.razao_social": "Razão social:",
            "fornecedor.nome_fantasia": "Nome fantasia:",
            "fornecedor.cnpj": "CNPJ:",
            "fornecedor.sla_atendimento": "SLA de atendimento:",
            "fornecedor.categorias": "Categorias",
            "fornecedor.confirmar_exclusao": "Deseja realmente excluir este fornecedor?",
            "fornecedor.cadastro_sucesso": "Fornecedor cadastrado com sucesso!",
            "fornecedor.erro_entrada": "Erro: Entrada inválida. Tente novamente.",
            "fornecedor.selecione_na lista": "Selecione um fornecedor na lista.",
            "fornecedor.atualizacao_sucesso": "Fornecedor atualizado com sucesso!",
            "fornecedor.exclusao_sucesso": "Fornecedor excluído com sucesso!",
            "fornecedor.nao_encontrado": "Fornecedor não encontrado.",
            "fornecedor.problema_exclusao": "Problemas ao excluir fornecedor",
            "fornecedor.cadastre_categorias": "Cadastre categorias antes de associá-las a um fornecedor.",
            "fornecedor.atualizacao_categoria": "Categorias do fornecedor atualizadas com sucesso!",
            "fornecedor.erro_salvar_cat": "Não foi possível salvar as categorias do fornecedor.",
            "fornecedor.erro_valor_negativo": "O SLA de atendimento não pode ser negativo.",
            "fornecedor.cadastre_perfis_antes": "Cadastre perfis antes de associá-los a um fornecedor.",
            "fornecedor.perfil_forne_atualizado": "Perfis do fornecedor atualizados com sucesso!",
            "fornecedor.marcar/desmarcar_fornecedor": "Clique para marcar/desmarcar as categorias deste fornecedor:",
            "fornecedor.titulo": "Categorias de",

            # Tela de Categoria
            "categoria.cadastro_sucesso": "Categoria cadastrada com sucesso!",
            "categoria.selecionar_categoria": "Selecione uma categoria na lista.",
            "categoria.atualizacao_sucesso": "Categoria atualizada com sucesso!",
            "categoria.exclusao_sucesso": "Categoria excluída com sucesso!",
            "categoria.nao_encontrada": "Categoria não encontrada.",
            "categoria.problemas_exclusao": "Problemas ao excluir categoria",
            "categoria.janela_titulo": "CRUD de Categorias",
            "categoria.titulo": "Cadastro de Categorias",
            "categoria.dados_frame": "Dados da categoria",
            "categoria.confirmar_exclusao": "Deseja realmente excluir esta categoria?",
            
            # Tela de Cidades
            "cidade.janela_titulo":"CRUD de Cidades",
            "cidade.titulo": "Cadastro de Cidades",
            "cidade.dados_frame": "Dados da cidade",
            "cidade.confirmar_exclusao": "Deseja realmente excluir esta cidade?",
            "cidade.cadastro_sucesso": "Cidade cadastrada com sucesso!",
            "cidade.selecionar_cidade": "Selecione uma cidade na lista.",
            "cidade.atualizacao_sucesso": "Cidade atualizada com sucesso!",
            "cidade.exclusao_concluida": "Cidade excluída com sucesso!",
            "cidade.nao_cadastrada": "Cidade não encontrada.",
            "cidade.problemas_exclusao": "Problemas ao excluir cidade",
            "cidade.selecione_estado": "Selecione um estado.",
            
            # Telas de Clientes 
            "cliente.limite_negativo": "O limite não pode ser negativo.",
            "cliente.janela_titulo": "CRUD de Clientes",
            "cliente.titulo": "Cadastro de Clientes",
            "cliente.dados_frame": "Dados do cliente",
            "cliente.data_nascimento": "Nascimento (DD/MM/AAAA):",
            "cliente.limite_credito": "Limite de crédito:",
            "cliente.estado": "Estado:",
            "cliente.cidade": "Cidade:",
            "cliente.confirmar_exclusao": "Deseja realmente excluir este cliente?",
            "cliente.data_nascimento_invalida": "Data de nascimento inválida. Use o formato DD/MM/AAAA.",
            "cliente.selecione_cidade": "Selecione uma cidade.",
            "cliente.cadastro_sucesso": "Cliente cadastrado com sucesso!",
            "cliente.selecione_cliente": "Selecione um cliente na lista.",
            "cliente.atualizacao_sucesso": "Cliente atualizado com sucesso!",
            "cliente.exclusao_concluida": "Cliente excluído com sucesso!",
            "cliente.nao_encontrado": "Cliente não encontrado.",
            "cliente.problema_exclusao": "Problemas ao excluir cliente",
            "cliente.idade": "Idade",

            #Tela de usuario
            "usuario.janela_titulo": "CRUD de Usuários",
            "usuario.titulo": "Cadastro de Usuários",
            "usuario.dados_frame": "Dados do usuário",
            "usuario.perfil": "Perfil:",
            "usuario.email": "Email:",
            "usuario.daat_nascimento": "Nascimento (DD/MM/AAAA):",
            "usuario.estado": "Estado:",
            "usuario.cidade": "Cidade:",
            "usuario.confirmar_exclusao":"Deseja realmente excluir este usuário?",
            "usuario.data_nascimetno_invalida": "Data de nascimento inválida. Use o formato DD/MM/AAAA.",
            "usuario.selecione_cidade": "Selecione uma cidade.",
            "usuario.selecione_perfil": "Selecione um perfil.",
            "usuario.cadastro_sucesso": "Usuário cadastrado com sucesso!",
            "usuario.selecione_usuario": "Selecione um usuário na lista.",
            "usuario.atualizado_sucesso": "Usuário atualizado com sucesso!",
            "usuario.exclusao_sucesso": "Usuário excluído com sucesso!",
            "usuario.nao_encontrado": "Usuário não encontrado.",
            "usuario.problema_exclusao": "Problemas ao excluir usuário",
            "usuario.idade": "Idade",

            #Tela de Produto
            "produto.preco_nao_negativo": "O preço não pode ser negativo.",
            "produto.estoque_nao_negativo": "O estoque não pode ser negativo.",
            "produto.janela_titulo": "CRUD de Produtos",
            "produto.titulo": "Cadastro de Produtos",
            "produto.dados_frame":"Dados do produto",
            "produto.fornecedor": "Fornecedor:",
            "produto.estoque": "Estoque:",
            "produto.preco": "Preço:",
            "produto.confirmar_exclusao": "Deseja realmente excluir este produto?",
            "produto.selecionar_fornecedor": "Selecione um fornecedor.",
            "produto.cadastro_sucesso": "Produto cadastrado com sucesso!",
            "produto.selecione_produto": "Selecione um produto na lista.",
            "produto.produto_atualizado": "Produto atualizado com sucesso!",
            "produto.produto_excluido": "Produto excluído com sucesso!",
            "produto.nao_encontrado": "Produto não encontrado.",
            "produto.problema_exclusao": "Problemas ao excluir produto", 
            "produto.valor_estoque": "Valor em estoque",

            #Telas de Perfis
            "perfis.janela_titulo":"CRUD de Perfis",
            "perfis.titulo":"CRUD de Perfis",
            "perfis.dados_frame":"CRUD de Perfis",
            "perfis.descricao": "Descrição:",
            "perfis.confirmacao_exclusao": "Deseja realmente excluir este perfil?",
            "perfis.perfis_cadastrados": "Perfis cadastrados com sucesso!",
            "perfis.selecione_perfil":"Selecione um perfil na lista.",
            "perfis.perfil_atualizado":"Perfil atualizado com sucesso!",
            "perfis.perfil_excluido":"Perfil excluido com sucesso!",
            "perfis.nao_encontrado":"Perfil não encontrado.",
            "perfis.problema_exclusao":"Problemas ao excluir perfil",
            
            # Tela de Perfil_Fornecedor 
            "perfil_fornecedor.janela_titulo":"Fornecedores do perfil",
            "perfil_fornecedor.titulo": "Fornecedores do perfil",
            "perfil_fornecedor.marcar_desmarcar_fornecedor": "Clique para marcar/desmarcar os fornecedores deste perfil:",
            "perfil_fornecedor.erro_carregar_forne": "Erro ao carregar fornecedores:",
            "perfil_fornecedor.fornecedor_perfil_atualizado": "Fornecedores do perfil atualizados com sucesso!",
            "perfil_fornecedor.erro_salvar":"Erro ao salvar fornecedores:",

            # Menu principal
            "menu.cadastros_basicos": "Cadastros básicos",
            "menu.estados": "Estados",
            "menu.cidades": "Cidades",
            "menu.acessos": "Acessos",
            "menu.usuarios": "Usuários",
            "menu.perfis": "Perfis",
            "menu.gestao_estoque": "Gestão de estoque",
            "menu.clientes": "Clientes",
            "menu.fornecedores": "Fornecedores",
            "menu.produtos": "Produtos",
            "menu.categorias": "Categorias",
            "menu.idioma": "Idioma",
            "menu.sair": "Sair",
        },
        "en": { #ingles

            # Common to several screens
            "comum.id": "ID",
            "comum.nome": "Name",
            "comum.novo": "New",
            "comum.salvar": "Save",
            "comum.alterar": "Edit",
            "comum.excluir": "Delete",
            "comum.fechar": "Close",
            "comum.cancelar": "Cancel",
            "comum.confirmacao": "Confirmation",
            "comum.erro_prefixo": "Error: ",

             # States screen
            "estado.janela_titulo": "State Management",
            "estado.titulo": "State Registration",
            "estado.dados_frame": "State data",
            "estado.sigla": "Abbreviation",
            "estado.confirmar_exclusao": "Do you really want to delete this state?",
            "estado.cadastrado_sucesso": "State registered successfully!",
            "estado.atualizado_sucesso": "State updated successfully!",
            "estado.excluido_sucesso": "State deleted successfully!",
            "estado.nao_encontrado": "State not found.",
            "estado.selecione_da_lista": "Select a state from the list.",
            "estado.erro_ao_excluir": "Problem deleting state",
            "estado.erro_sigla_tamanho": "The abbreviation must have exactly 2 characters.",

            # Suppliers screen 
            "fornecedor.janela_titulo": "Suppliers screen",
            "fornecedor.titulo": "Suppliers registration",
            "fornecedor.dados_frame": "Suppliers data",
            "fornecedor.razao_social": "Legal name:", 
            "fornecedor.nome_fantasia": "Trade name:",
            "fornecedor.cnpj": "CNPJ:",
            "fornecedor.sla_atendimento":"Service SLA:", 
            "fornecedor.categorias": "Categories",
            "fornecedor.confirmar_exclusao": "Do you really want to delete this supplier?",
            "fornecedor.cadastro_sucesso": "Supplier successfully registered!",
            "fornecedor.erro_entrada": "Error: Invalid input. Please try again.",
            "fornecedor.selecione_na lista": "Select a supplier from the list.",
            "fornecedor.atualizacao_sucesso": "Supplier updated successfully!",
            "fornecedor.exclusao_sucesso": "Supplier deleted successfully!",
            "fornecedor.nao_encontrado": "Supplier not found.",
            "fornecedor.problema_exclusao": "Problem deleting supplier",
            "fornecedor.cadastre_categorias": "Register categories before associating them with a supplier.",
            "fornecedor.atualizacao_categoria": "Supplier categories updated successfully!",
            "fornecedor.erro_salvar_cat": "Could not save supplier categories.",
            "fornecedor.erro_valor_negativo": "Service SLA cannot be negative.",

             # Tela de Categoria
            "categoria.cadastro_sucesso": "Category registered successfully!",
            "categoria.selecionar_categoria": "Select a category from the list.",
            "categoria.atualizacao_sucesso": "Category updated successfully!",
            "categoria.exclusao_sucesso": "Category deleted successfully!",
            "categoria.nao_encontrada": "Category not found.",
            "categoria.problemas_exclusao": "Error deleting category",
            "categoria.janela_titulo": "Category CRUD",
            "categoria.titulo": "Category Registration",
            "categoria.dados_frame": "Category details",
            "categoria.confirmar_exclusao": "Are you sure you want to delete this category?",

            # Cities screen 
            "cidade.janela_titulo":"City CRUD",
            "cidade.titulo": "City Registration", 
            "cidade.dados_frame": "City data", 
            "cidade.confirmar_exclusao": "Are you sure you want to delete this city?", 
            "cidade.cadastro_sucesso": "City registered successfully!", 
            "cidade.selecionar_cidade": "Select a city from the list.", 
            "cidade.atualizacao_sucesso": "City updated successfully!", 
            "cidade.exclusao_concluida": "City deleted successfully!", 
            "cidade.nao_cadastrada": "City not found.", 
            "cidade.problemas_exclusao": "Error deleting city",

            # Telas de Clientes 
            "cliente.limite_negativo": "The limit cannot be negative.", 
            "cliente.janela_titulo": "Customer CRUD", 
            "cliente.titulo": "Customer Registration", 
            "cliente.dados_frame": "Customer details", 
            "cliente.data_nascimento": "Date of birth (DD/MM/YYYY):", 
            "cliente.limite_credito": "Credit limit:", 
            "cliente.estado": "State:", 
            "cliente.cidade": "City:", 
            "cliente.confirmar_exclusao": 
            "Are you sure you want to delete this customer?", 
            "cliente.data_nascimento_invalida": "Invalid date of birth. Use the format DD/MM/YYYY.", 
            "cliente.selecione_cidade": "Select a city.", 
            "cliente.cadastro_sucesso": "Customer registered successfully!", 
            "cliente.selecione_cliente": "Select a customer from the list.", 
            "cliente.atualizacao_sucesso": "Customer updated successfully!", 
            "cliente.exclusao_concluida": "Customer deleted successfully!", 
            "cliente.nao_encontrado": "Customer not found.", 
            "cliente.problema_exclusao": "Error deleting customer",

             #User screen 
            "usuario.janela_titulo": "User CRUD", 
            "usuario.titulo": "User Registration", 
            "usuario.dados_frame": "User details", 
            "usuario.perfil": "Profile:", 
            "usuario.email": "Email:", 
            "usuario.daat_nascimento": 
            "Date of birth (DD/MM/YYYY):", 
            "usuario.estado": "State:", 
            "usuario.cidade": "City:", 
            "usuario.confirmar_exclusao":"Are you sure you want to delete this user?", 
            "usuario.data_nascimetno_invalida": "Invalid date of birth. Use the format DD/MM/YYYY.", 
            "usuario.selecione_cidade": "Select a city.", 
            "usuario.selecione_perfil": "Select a profile.", 
            "usuario.cadastro_sucesso": "User registered successfully!", 
            "usuario.selecione_usuario": "Select a user from the list.", 
            "usuario.atualizado_sucesso": "User updated successfully!", 
            "usuario.exclusao_sucesso": "User deleted successfully!", 
            "usuario.nao_encontrado": "User not found.", 
            "usuario.problema_exclusao": "Error deleting user",

            # Product screen 
            "produto.preco_nao_negativo": "The price cannot be negative.",
            "produto.estoque_nao_negativo": "The stock level cannot be negative.",
            "produto.janela_titulo": "Product CRUD",
            "produto.titulo": "Product Registration",
            "produto.dados_frame": "Product details",
            "produto.fornecedor": "Supplier:",
            "produto.estoque": "Stock:",
            "produto.preco": "Price:",
            "produto.confirmar_exclusao": "Are you sure you want to delete this product?",
            "produto.selecionar_fornecedor": "Select a supplier.",
            "produto.cadastro_sucesso": "Product registered successfully!",
            "produto.selecione_produto": "Select a product from the list.",
            "produto.produto_atualizado": "Product updated successfully!",
            "produto.produto_excluido": "Product deleted successfully!",
            "produto.nao_encontrado": "Product not found.",
            "produto.problema_exclusao": "Error deleting product",

             #Telas de Perfis
            "perfis.janela_titulo":"Profile CRUD", 
            "perfis.titulo":"Profile CRUD", 
            "perfis.dados_frame":"Profile CRUD", 
            "perfis.descricao": "Description:", 
            "perfis.confirmacao_exclusao": "Are you sure you want to delete this profile?", 
            "perfis.perfis_cadastrados": "Profile successfully registered!", 
            "perfis.selecione_perfil":"Select a profile from the list.", 
            "perfis.perfil_atualizado":"Profile successfully updated!", 
            "perfis.perfil_excluido":"Profile successfully deleted!", 
            "perfis.nao_encontrado":"Profile not found.", 
            "perfis.problema_exclusao":"Error deleting profile",
            
            # Tela de Perfil_Fornecedor
            "perfil_fornecedor.janela_titulo":"Profile Suppliers", 
            "perfil_fornecedor.titulo": "Profile Suppliers", 
            "perfil_fornecedor.marcar_desmarcar_fornecedor": "Click to select/deselect suppliers for this profile:", 
            "perfil_fornecedor.erro_carregar_forne": "Error loading suppliers:", 
            "perfil_fornecedor.fornecedor_perfil_atualizado": "Profile suppliers successfully updated!", 
            "perfil_fornecedor.erro_salvar":"Error saving suppliers:",

            # Main menu
            "menu.cadastros_basicos": "Basic registrations",
            "menu.estados": "States",
            "menu.cidades": "Cities",
            "menu.acessos": "Access",
            "menu.usuarios": "Users",
            "menu.perfis": "Roles",
            "menu.gestao_estoque": "Inventory management",
            "menu.clientes": "Customers",
            "menu.fornecedores": "Suppliers",
            "menu.produtos": "Products",
            "menu.categorias": "Categories",
            "menu.idioma": "Language",
            "menu.sair": "Exit",
        }
    }

    @classmethod # é usado quando tem algum atributo que eu quero que os metodos acessem e modifiquem eles
    def definir(cls, codigo): #cls = um self, que eu passo a propria classe como referencia
        cls.ATUAL = codigo # no codigo eu determino o idioma 

    @classmethod
    def t(cls, chave): # t = é um metodo normalmente de tradução 
        return cls.TEXTOS[cls.ATUAL].get(chave, chave)

